/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TripRouteImport } from './routes/trip'
import { Route as SosRouteImport } from './routes/sos'
import { Route as SetupRouteImport } from './routes/setup'
import { Route as OfflineRouteImport } from './routes/offline'
import { Route as NearbyRouteImport } from './routes/nearby'
import { Route as MedicalRouteImport } from './routes/medical'
import { Route as HomeRouteImport } from './routes/home'
import { Route as GuidanceRouteImport } from './routes/guidance'
import { Route as EmergencyRouteImport } from './routes/emergency'
import { Route as ContactsRouteImport } from './routes/contacts'
import { Route as AnalysisRouteImport } from './routes/analysis'
import { Route as IndexRouteImport } from './routes/index'

const TripRoute = TripRouteImport.update({
  id: '/trip',
  path: '/trip',
  getParentRoute: () => rootRouteImport,
} as any)
const SosRoute = SosRouteImport.update({
  id: '/sos',
  path: '/sos',
  getParentRoute: () => rootRouteImport,
} as any)
const SetupRoute = SetupRouteImport.update({
  id: '/setup',
  path: '/setup',
  getParentRoute: () => rootRouteImport,
} as any)
const OfflineRoute = OfflineRouteImport.update({
  id: '/offline',
  path: '/offline',
  getParentRoute: () => rootRouteImport,
} as any)
const NearbyRoute = NearbyRouteImport.update({
  id: '/nearby',
  path: '/nearby',
  getParentRoute: () => rootRouteImport,
} as any)
const MedicalRoute = MedicalRouteImport.update({
  id: '/medical',
  path: '/medical',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeRoute = HomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => rootRouteImport,
} as any)
const GuidanceRoute = GuidanceRouteImport.update({
  id: '/guidance',
  path: '/guidance',
  getParentRoute: () => rootRouteImport,
} as any)
const EmergencyRoute = EmergencyRouteImport.update({
  id: '/emergency',
  path: '/emergency',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactsRoute = ContactsRouteImport.update({
  id: '/contacts',
  path: '/contacts',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalysisRoute = AnalysisRouteImport.update({
  id: '/analysis',
  path: '/analysis',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/analysis': typeof AnalysisRoute
  '/contacts': typeof ContactsRoute
  '/emergency': typeof EmergencyRoute
  '/guidance': typeof GuidanceRoute
  '/home': typeof HomeRoute
  '/medical': typeof MedicalRoute
  '/nearby': typeof NearbyRoute
  '/offline': typeof OfflineRoute
  '/setup': typeof SetupRoute
  '/sos': typeof SosRoute
  '/trip': typeof TripRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/analysis': typeof AnalysisRoute
  '/contacts': typeof ContactsRoute
  '/emergency': typeof EmergencyRoute
  '/guidance': typeof GuidanceRoute
  '/home': typeof HomeRoute
  '/medical': typeof MedicalRoute
  '/nearby': typeof NearbyRoute
  '/offline': typeof OfflineRoute
  '/setup': typeof SetupRoute
  '/sos': typeof SosRoute
  '/trip': typeof TripRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/analysis': typeof AnalysisRoute
  '/contacts': typeof ContactsRoute
  '/emergency': typeof EmergencyRoute
  '/guidance': typeof GuidanceRoute
  '/home': typeof HomeRoute
  '/medical': typeof MedicalRoute
  '/nearby': typeof NearbyRoute
  '/offline': typeof OfflineRoute
  '/setup': typeof SetupRoute
  '/sos': typeof SosRoute
  '/trip': typeof TripRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/analysis'
    | '/contacts'
    | '/emergency'
    | '/guidance'
    | '/home'
    | '/medical'
    | '/nearby'
    | '/offline'
    | '/setup'
    | '/sos'
    | '/trip'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/analysis'
    | '/contacts'
    | '/emergency'
    | '/guidance'
    | '/home'
    | '/medical'
    | '/nearby'
    | '/offline'
    | '/setup'
    | '/sos'
    | '/trip'
  id:
    | '__root__'
    | '/'
    | '/analysis'
    | '/contacts'
    | '/emergency'
    | '/guidance'
    | '/home'
    | '/medical'
    | '/nearby'
    | '/offline'
    | '/setup'
    | '/sos'
    | '/trip'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AnalysisRoute: typeof AnalysisRoute
  ContactsRoute: typeof ContactsRoute
  EmergencyRoute: typeof EmergencyRoute
  GuidanceRoute: typeof GuidanceRoute
  HomeRoute: typeof HomeRoute
  MedicalRoute: typeof MedicalRoute
  NearbyRoute: typeof NearbyRoute
  OfflineRoute: typeof OfflineRoute
  SetupRoute: typeof SetupRoute
  SosRoute: typeof SosRoute
  TripRoute: typeof TripRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/trip': {
      id: '/trip'
      path: '/trip'
      fullPath: '/trip'
      preLoaderRoute: typeof TripRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sos': {
      id: '/sos'
      path: '/sos'
      fullPath: '/sos'
      preLoaderRoute: typeof SosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/setup': {
      id: '/setup'
      path: '/setup'
      fullPath: '/setup'
      preLoaderRoute: typeof SetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/offline': {
      id: '/offline'
      path: '/offline'
      fullPath: '/offline'
      preLoaderRoute: typeof OfflineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nearby': {
      id: '/nearby'
      path: '/nearby'
      fullPath: '/nearby'
      preLoaderRoute: typeof NearbyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/medical': {
      id: '/medical'
      path: '/medical'
      fullPath: '/medical'
      preLoaderRoute: typeof MedicalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home': {
      id: '/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof HomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guidance': {
      id: '/guidance'
      path: '/guidance'
      fullPath: '/guidance'
      preLoaderRoute: typeof GuidanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/emergency': {
      id: '/emergency'
      path: '/emergency'
      fullPath: '/emergency'
      preLoaderRoute: typeof EmergencyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contacts': {
      id: '/contacts'
      path: '/contacts'
      fullPath: '/contacts'
      preLoaderRoute: typeof ContactsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analysis': {
      id: '/analysis'
      path: '/analysis'
      fullPath: '/analysis'
      preLoaderRoute: typeof AnalysisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AnalysisRoute: AnalysisRoute,
  ContactsRoute: ContactsRoute,
  EmergencyRoute: EmergencyRoute,
  GuidanceRoute: GuidanceRoute,
  HomeRoute: HomeRoute,
  MedicalRoute: MedicalRoute,
  NearbyRoute: NearbyRoute,
  OfflineRoute: OfflineRoute,
  SetupRoute: SetupRoute,
  SosRoute: SosRoute,
  TripRoute: TripRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
